### ISSUE TITLE
Minor issue with postinst

### ISSUE THREAD

**Issue by zmarano** [GoogleCloudPlatform/osconfig#398]
```touch: cannot touch ‘/var/lib/google_osconfig_agent/osconfig_agent_restart_required’: No such file or directory
warning: %post(google-osconfig-agent-1:20210930.00-g1.el7.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package 1:google-osconfig-agent-20210930.00-g1.el7.x86_64
```

**Comment by adjackura** [comment]
This should be resolved in recent packages

**Comment by hgpit** [comment]
Am still encountering this today on GCP when updating a Rocky 8 VM (Google-provided image).
